//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.6.1055.0.
// 
namespace CSNXML.CSNModels {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.csn.se/Studeranderapport")]
    [System.Xml.Serialization.XmlRootAttribute("studeranderapport", Namespace="http://schema.csn.se/Studeranderapport", IsNullable=false)]
    public partial class StuderanderapportTyp {
        
        private SkolaTyp skolaField;
        
        /// <remarks/>
        public SkolaTyp skola {
            get {
                return this.skolaField;
            }
            set {
                this.skolaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.csn.se/Studeranderapport")]
    public partial class SkolaTyp {
        
        private int skolIdField;
        
        private StuderandeTyp[] studerandeField;
        
        /// <remarks/>
        public int skolId {
            get {
                return this.skolIdField;
            }
            set {
                this.skolIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("studerande")]
        public StuderandeTyp[] studerande {
            get {
                return this.studerandeField;
            }
            set {
                this.studerandeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.csn.se/Studeranderapport")]
    public partial class StuderandeTyp {
        
        private string personnummerField;
        
        private StudieperiodTyp[] studieperiodField;
        
        /// <remarks/>
        public string personnummer {
            get {
                return this.personnummerField;
            }
            set {
                this.personnummerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("studieperiod")]
        public StudieperiodTyp[] studieperiod {
            get {
                return this.studieperiodField;
            }
            set {
                this.studieperiodField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schema.csn.se/Studeranderapport")]
    public partial class StudieperiodTyp {
        
        private System.DateTime fromDatumField;
        
        private System.DateTime tomDatumField;
        
        private float omfattningField;
        
        private string resultatField;
        
        private System.DateTime resultatDatumField;
        
        private bool resultatDatumFieldSpecified;
        
        private System.DateTime andringsDatumField;
        
        private bool andringsDatumFieldSpecified;
        
        private System.DateTime avbrottsDatumField;
        
        private bool avbrottsDatumFieldSpecified;
        
        private string uppdragsutbildningField;
        
        private string resultatAvbrottField;
        
        private string avdelningField;
        
        private string nivaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime fromDatum {
            get {
                return this.fromDatumField;
            }
            set {
                this.fromDatumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime tomDatum {
            get {
                return this.tomDatumField;
            }
            set {
                this.tomDatumField = value;
            }
        }
        
        /// <remarks/>
        public float omfattning {
            get {
                return this.omfattningField;
            }
            set {
                this.omfattningField = value;
            }
        }
        
        /// <remarks/>
        public string resultat {
            get {
                return this.resultatField;
            }
            set {
                this.resultatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime resultatDatum {
            get {
                return this.resultatDatumField;
            }
            set {
                this.resultatDatumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool resultatDatumSpecified {
            get {
                return this.resultatDatumFieldSpecified;
            }
            set {
                this.resultatDatumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime andringsDatum {
            get {
                return this.andringsDatumField;
            }
            set {
                this.andringsDatumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool andringsDatumSpecified {
            get {
                return this.andringsDatumFieldSpecified;
            }
            set {
                this.andringsDatumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime avbrottsDatum {
            get {
                return this.avbrottsDatumField;
            }
            set {
                this.avbrottsDatumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool avbrottsDatumSpecified {
            get {
                return this.avbrottsDatumFieldSpecified;
            }
            set {
                this.avbrottsDatumFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string uppdragsutbildning {
            get {
                return this.uppdragsutbildningField;
            }
            set {
                this.uppdragsutbildningField = value;
            }
        }
        
        /// <remarks/>
        public string resultatAvbrott {
            get {
                return this.resultatAvbrottField;
            }
            set {
                this.resultatAvbrottField = value;
            }
        }
        
        /// <remarks/>
        public string avdelning {
            get {
                return this.avdelningField;
            }
            set {
                this.avdelningField = value;
            }
        }
        
        /// <remarks/>
        public string niva {
            get {
                return this.nivaField;
            }
            set {
                this.nivaField = value;
            }
        }
    }
}
